# Generated by Django 5.1.7 on 2025-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
