# Generated by Django 5.1.7 on 2025-04-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_remove_profile_created_at_remove_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
