# Generated by Django 5.1.7 on 2025-04-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_component_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentcheckout',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
