# Generated by Django 5.1.7 on 2025-04-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_componentcheckout_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentcheckout',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
